env:
  TERM: xterm-256color

font:
  normal:
    family: mononoki nerd font mono
    style: Regular
  bold:
    family: mononoki nerd font mono
    style: Bold
  italic:
    family: mononoki nerd font mono
    style: Italic
  bold_italic:
    family: mononoki nerd font mono
    style: Bold Italic
  size: 13.0

# Nord Theme
#colors:
#primary:
#background: "#2e3440"
#foreground: "#d8dee9"
#dim_foreground: "#a5abb6"
#cursor:
#text: "#2e3440"
#cursor: "#d8dee9"
#vi_mode_cursor:
#text: "#2e3440"
#cursor: "#d8dee9"
#selection:
#text: CellForeground
#background: "#4c566a"
#search:
#matches:
#foreground: CellBackground
#background: "#88c0d0"
#bar:
#background: "#434c5e"
#foreground: "#d8dee9"
#normal:
#black: "#3b4252"
#red: "#bf616a"
#green: "#a3be8c"
#yellow: "#ebcb8b"
#blue: "#81a1c1"
#magenta: "#b48ead"
#cyan: "#88c0d0"
#white: "#e5e9f0"
#bright:
#black: "#4c566a"
#red: "#bf616a"
#green: "#a3be8c"
#yellow: "#ebcb8b"
#blue: "#81a1c1"
#magenta: "#b48ead"
#cyan: "#8fbcbb"
#white: "#eceff4"
#dim:
#black: "#373e4d"
#red: "#94545d"
#green: "#809575"
#yellow: "#b29e75"
#blue: "#68809a"
#magenta: "#8c738c"
#cyan: "#6d96a5"
#white: "#aeb3bb"

# Colors (One Dark)
colors:
  # Default colors
  primary:
    background: "0x1e2127"
    foreground: "0xabb2bf"

  # Normal colors
  normal:
    black: "0x1e2127"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xd19a66"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0xabb2bf"

  # Bright colors
  bright:
    black: "0x5c6370"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xd19a66"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0xffffff"

window:
  opacity: 0.95
