# -*- mode: ruby -*-
# vi: set ft=ruby :

required_plugins = %w[vagrant-libvirt]
required_plugins.each do |plugin|
  unless Vagrant.has_plugin?(plugin)
    system "vagrant plugin install #{plugin}"
    exit
  end
end

Vagrant.configure("2") do |config|
  config.vm.provider "libvirt" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.define "arch" do |m|
    m.vm.box = "arch"
  end

  config.vm.define "debian" do |m|
    m.vm.box = "debian"
  end
end
