--ozone-platform-hint=auto
--use-gl=angle
--use-angle=gl
--ignore-gpu-blocklist
--disable-gpu-driver-bug-workaround
--enable-features=AcceleratedVideoEncoder,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,VaapiOnNvidiaGPUs
