#!/bin/bash

while true; do
    player_status=$(playerctl status 2> /dev/null)
    content=""
    if [ -z "$(playerctl metadata album 2> /dev/null)" ]; then
        if [ "$player_status" = "Playing" ]; then
            content="$(playerctl metadata artist) - $(playerctl metadata title)"
        elif [ "$player_status" = "Paused" ]; then
            content=" $(playerctl metadata artist) - $(playerctl metadata title)"
        else
            content=""
        fi
    else
        if [ "$player_status" = "Playing" ]; then
            content="$(playerctl metadata artist) - $(playerctl metadata title)"
        elif [ "$player_status" = "Paused" ]; then
            content=" $(playerctl metadata artist) - $(playerctl metadata title)"
        else
            content=""
        fi
    fi
    echo "${content::25}"

    sleep 1
done
